import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Card from '@/components/card/card'
import Footer from '@/components/Layout_Items/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT Sea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen place-items-center">
        <Card />
      </div>
      <Footer />
    </>
  )
}
