import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
// import { Cinzel_700Bold } from '../public/fonts/Cinzel_700Bold.ttf'
// import { OpenSans_400Regular, OpenSans_600SemiBold } from '@fontsource/open-sans';
import { useEthers } from '@usedapp/core'
import dynamic from 'next/dynamic'

interface CustomWindow extends Window {
  ethereum?: any
}

const WalletInstallation = dynamic(
  () =>
    import('@/components/User_Profile/Wallet_Installation/walletInstallation'),
  { ssr: false }
)

export default function Home() {
  const [ethereum, setEthereum] = useState(null)
  const { activateBrowserWallet, account } = useEthers()

  useEffect(() => {
    setEthereum((window as CustomWindow).ethereum)
  }, [])

  return (
    <>
      <Head>
        <title>NFT Sea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {!ethereum ? <WalletInstallation /> : null}
      </div>
      <div>
        <p>Account: {account}</p>
        {/* <p>Chain ID: {chainId}</p>
        <p>Balance: {etherBalance}</p> */}
      </div>
      <div>
        <div>
          <button onClick={() => activateBrowserWallet()}>Connect</button>
        </div>
        {account && <p>Account: {account}</p>}
      </div>
    </>
  )
}
